// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureDataset() {
  return window['go']['main']['App']['EnsureDataset']();
}

export function GetDataset() {
  return window['go']['main']['App']['GetDataset']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
