// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureDataset():Promise<void>;

export function GetDataset():Promise<Array<string>>;

export function GetVersion():Promise<number>;
